name: gh-action
on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install ".[test]"
      - name: Run tests
        run: pytest tests
